// Where each Modrinth project is listed. Every entry counts as correct, and an empty list means none.
export interface Listings {
	curseforge: string[]
	hangar: string[]
	spigot: number[]
}

// Each entry was checked by hand or is backed by a shared source repository or author.
export const CASES: Record<string, Listings> = {
	// Plugins
	'advanced-backups': {
		curseforge: ['mc-mods/advanced-backups'],
		hangar: ['HeatherWhite/AdvancedBackups'],
		spigot: [],
	},
	auraskills: { curseforge: [], hangar: ['Archy/AuraSkills'], spigot: [81069] },
	authmerereloaded: { curseforge: [], hangar: ['0D00_0721/AuthMeReReloaded'], spigot: [] },
	axgraves: {
		curseforge: ['bukkit-plugins/axgraves'],
		hangar: ['Artillex-Studios/AxGraves'],
		spigot: [113629],
	},
	'axiom-paper-plugin': { curseforge: [], hangar: [], spigot: [] },
	'better-boat-movement': { curseforge: ['mc-mods/better-boat-movement'], hangar: [], spigot: [] },
	bluemap: { curseforge: ['mc-mods/bluemap'], hangar: ['Blue/BlueMap'], spigot: [83557] },
	buildpaste: {
		curseforge: ['bukkit-plugins/buildpaste', 'mc-mods/buildpaste'],
		hangar: [],
		spigot: [],
	},
	calcmod: { curseforge: ['mc-mods/calcmod'], hangar: [], spigot: [] },
	chunky: {
		curseforge: [
			'mc-mods/chunky-pregenerator-forge',
			'mc-mods/chunky-pregenerator',
			'bukkit-plugins/chunky-pregenerator',
		],
		hangar: ['pop4959/Chunky'],
		spigot: [81534],
	},
	chunkyborder: {
		curseforge: ['mc-mods/chunky-border', 'bukkit-plugins/chunky-border'],
		hangar: [],
		spigot: [],
	},
	'clearlag++': { curseforge: ['bukkit-plugins/clearlagplusplus'], hangar: [], spigot: [127506] },
	clickmobs: { curseforge: ['mc-mods/clickmobs'], hangar: [], spigot: [] },
	clickvillagers: { curseforge: ['mc-mods/clickvillagers'], hangar: [], spigot: [] },
	'common-network': { curseforge: ['mc-mods/common-network'], hangar: [], spigot: [] },
	coreprotect: {
		curseforge: ['bukkit-plugins/coreprotect'],
		hangar: ['CORE/CoreProtect'],
		spigot: [8631],
	},
	crazycrates: {
		curseforge: ['bukkit-plugins/crazycrates'],
		hangar: ['CrazyCrew/CrazyCrates'],
		spigot: [],
	},
	crazyenchantments: { curseforge: [], hangar: ['CrazyCrew/CrazyEnchantments'], spigot: [] },
	'custom-player-models': {
		curseforge: [
			'mc-mods/custom-player-models',
			'mc-mods/custom-player-models-fabric',
			'mc-mods/cpmsvcc',
			'mc-mods/cpmoscc',
			'mc-mods/cpmpvc',
			'bukkit-plugins/custom-player-models-bukkit',
		],
		hangar: [],
		spigot: [],
	},
	customcrafting: {
		curseforge: ['bukkit-plugins/customcrafting-advanced-custom-recipes'],
		hangar: [],
		spigot: [55883, 95513],
	},
	dcintegration: {
		curseforge: [
			'mc-mods/dcintegration',
			'mc-mods/dcintegration-fabric',
			'bukkit-plugins/discordintegration-spigot',
		],
		hangar: [],
		spigot: [87196],
	},
	decentholograms: { curseforge: [], hangar: [], spigot: [96927] },
	discordsrv: { curseforge: [], hangar: [], spigot: [18494] },
	dynmap: { curseforge: ['bukkit-plugins/dynmap'], hangar: [], spigot: [274] },
	emotecraft: {
		curseforge: ['mc-mods/emotecraft', 'mc-mods/emotecraft-forge'],
		hangar: ['dima_dencep/emotecraft'],
		spigot: [],
	},
	essentialsx: { curseforge: ['bukkit-plugins/essentialsx'], hangar: [], spigot: [9089] },
	'essentialsx-chat-module': { curseforge: [], hangar: [], spigot: [] },
	'essentialsx-spawn': { curseforge: [], hangar: [], spigot: [] },
	fancyholograms: {
		curseforge: ['bukkit-plugins/fancyholograms'],
		hangar: ['Oliver/FancyHolograms'],
		spigot: [],
	},
	fancynpcs: {
		curseforge: ['bukkit-plugins/fancynpcs'],
		hangar: ['Oliver/FancyNpcs', 'Oliver/FancyNpcsModel'],
		spigot: [],
	},
	fastasyncworldedit: {
		curseforge: ['bukkit-plugins/fawe'],
		hangar: ['IntellectualSites/FastAsyncWorldEdit'],
		spigot: [13932],
	},
	fokusapi: { curseforge: [], hangar: [], spigot: [] },
	geyser: { curseforge: [], hangar: ['GeyserMC/Geyser'], spigot: [81297] },
	griefprevention: { curseforge: [], hangar: ['GriefPrevention/GriefPrevention'], spigot: [1884] },
	grimac: { curseforge: [], hangar: ['GrimAnticheat/GrimAnticheat'], spigot: [99923] },
	gsit: { curseforge: ['bukkit-plugins/gsit'], hangar: ['Gecolay/GSit'], spigot: [62325] },
	headpat: { curseforge: [], hangar: [], spigot: [] },
	huskhomes: {
		curseforge: ['mc-mods/huskhomes'],
		hangar: ['William278/HuskHomes'],
		spigot: [83767],
	},
	imageframe: { curseforge: [], hangar: ['LOOHP/ImageFrame'], spigot: [106031] },
	'infinite-villager-trading': { curseforge: [], hangar: [], spigot: [] },
	'invsee++': { curseforge: [], hangar: ['Jannyboy11/InvSee-plus-plus'], spigot: [82342] },
	itemedit: { curseforge: [], hangar: ['Emanon/ItemEdit'], spigot: [40993] },
	itemswapper: { curseforge: ['mc-mods/itemswapper'], hangar: [], spigot: [] },
	journeymap: {
		curseforge: ['bukkit-plugins/journeymap', 'mc-mods/journeymap'],
		hangar: ['mysticdrew/JourneyMap'],
		spigot: [],
	},
	'journeymap-teams': { curseforge: ['mc-mods/journeymap-teams'], hangar: [], spigot: [] },
	'just-tpa': { curseforge: ['bukkit-plugins/just-tpa'], hangar: [], spigot: [116325] },
	lagfixer: {
		curseforge: ['bukkit-plugins/lagfixer-free'],
		hangar: ['lajczik/LagFixer'],
		spigot: [111684],
	},
	'leashable-players': { curseforge: [], hangar: [], spigot: [] },
	legacyfreecam: { curseforge: ['mc-mods/freecam-fair-play'], hangar: [], spigot: [] },
	lifestealz: { curseforge: [], hangar: ['KartoffelChipss/LifestealZ'], spigot: [] },
	'lightning-grim-anticheat': { curseforge: [], hangar: [], spigot: [] },
	lmd: {
		curseforge: ['mc-mods/let-me-despawn', 'bukkit-plugins/let-me-despawn'],
		hangar: [],
		spigot: [],
	},
	luckperms: { curseforge: ['mc-mods/luckperms'], hangar: [], spigot: [28140] },
	maintenance: { curseforge: [], hangar: ['kennytv/Maintenance'], spigot: [40699] },
	mclogs: {
		curseforge: ['bukkit-plugins/mclogs', 'mc-mods/mclo-gs'],
		hangar: ['Aternos/mclogs'],
		spigot: [47502],
	},
	minimotd: { curseforge: [], hangar: ['jmp/MiniMOTD'], spigot: [81254] },
	modernnetworking: { curseforge: ['mc-mods/modernnetworking'], hangar: [], spigot: [] },
	'multiverse-core': {
		curseforge: ['bukkit-plugins/multiverse-core'],
		hangar: ['Multiverse/Multiverse-Core'],
		spigot: [390, 64450],
	},
	'multiverse-inventories': {
		curseforge: ['bukkit-plugins/multiverse-inventories'],
		hangar: ['Multiverse/Multiverse-Inventories'],
		spigot: [],
	},
	nbtapi: { curseforge: [], hangar: ['tr7zw/NBTAPI'], spigot: [] },
	nightcore: { curseforge: [], hangar: ['NightExpress/nightcore'], spigot: [] },
	oneblock_bukkit: { curseforge: [], hangar: [], spigot: [83215] },
	orebfuscator: {
		curseforge: ['bukkit-plugins/orebfuscator-anti-x-ray'],
		hangar: ['Imprex-Development/Orebfuscator'],
		spigot: [82710],
	},
	'osc-dp': { curseforge: ['data-packs/orbital-strike-cannon-datapack'], hangar: [], spigot: [] },
	otterlib: { curseforge: ['mc-mods/otterlib'], hangar: [], spigot: [] },
	packetevents: { curseforge: [], hangar: [], spigot: [80279] },
	patpat: { curseforge: ['mc-mods/patpat'], hangar: [], spigot: [] },
	placeholderapi: { curseforge: [], hangar: ['HelpChat/PlaceholderAPI'], spigot: [6245] },
	plan: {
		curseforge: ['mc-mods/plan-player-analytics'],
		hangar: ['AuroraLS3/Plan-Player-Analytics'],
		spigot: [32536],
	},
	'plasmo-voice': { curseforge: ['mc-mods/plasmo-voice'], hangar: [], spigot: [91064] },
	'playerkits-2': { curseforge: [], hangar: [], spigot: [112616] },
	powerranks: {
		curseforge: ['bukkit-plugins/powerranks'],
		hangar: ['PowerNetwork/PowerRanks'],
		spigot: [64696],
	},
	provanish: { curseforge: [], hangar: [], spigot: [] },
	'quickshop-hikari': { curseforge: [], hangar: [], spigot: [100125] },
	'server-redirect': {
		curseforge: ['bukkit-plugins/server-redirect', 'mc-mods/server-redirect'],
		hangar: [],
		spigot: [],
	},
	sethome: { curseforge: [], hangar: [], spigot: [111952] },
	'simple-login': { curseforge: ['bukkit-plugins/simple-login'], hangar: [], spigot: [] },
	'simple-voice-chat': {
		curseforge: ['bukkit-plugins/simple-voice-chat', 'mc-mods/simple-voice-chat'],
		hangar: ['henkelmax/SimpleVoiceChat'],
		spigot: [],
	},
	'simple-voice-chat-discord-bridge': { curseforge: [], hangar: [], spigot: [] },
	skbee: { curseforge: [], hangar: [], spigot: [138098] },
	skinsrestorer: { curseforge: [], hangar: ['SRTeam/SkinsRestorer'], spigot: [2124] },
	skript: {
		curseforge: ['bukkit-plugins/skript'],
		hangar: ['SkriptLang/Skript'],
		spigot: [114544],
	},
	smartspawner: { curseforge: [], hangar: ['Nighter/SmartSpawner'], spigot: [] },
	spark: { curseforge: ['mc-mods/spark'], hangar: [], spigot: [57242] },
	squaremap: { curseforge: [], hangar: ['jmp/squaremap'], spigot: [] },
	stairsit: { curseforge: [], hangar: [], spigot: [] },
	'string-dupers-return': { curseforge: ['mc-mods/string-dupers-return'], hangar: [], spigot: [] },
	'tab-was-taken': { curseforge: [], hangar: ['NEZNAMY/TAB'], spigot: [57806] },
	tabtps: { curseforge: [], hangar: ['jmp/TabTPS'], spigot: [82528] },
	terra: { curseforge: [], hangar: [], spigot: [85151] },
	'tps-hud': { curseforge: ['mc-mods/tps-hud-fabric'], hangar: [], spigot: [] },
	universetiertagger: { curseforge: [], hangar: [], spigot: [] },
	veinminer: { curseforge: ['mc-mods/veinminer-mod'], hangar: [], spigot: [] },
	'veinminer-enchantment': { curseforge: ['mc-mods/veinminer-enchant'], hangar: [], spigot: [] },
	viabackwards: { curseforge: [], hangar: ['ViaVersion/ViaBackwards'], spigot: [27448] },
	viarewind: {
		curseforge: ['mc-mods/viarewind'],
		hangar: ['ViaVersion/ViaRewind'],
		spigot: [52109],
	},
	viaversion: { curseforge: [], hangar: ['ViaVersion/ViaVersion'], spigot: [19254] },
	'villager-in-a-bucket': { curseforge: ['mc-mods/villager-in-a-bucket'], hangar: [], spigot: [] },
	voicemessages: { curseforge: [], hangar: ['DimasKama/VoiceMessages'], spigot: [] },
	'voxelmap-updated': { curseforge: [], hangar: [], spigot: [] },
	'voxy-server-side': { curseforge: [], hangar: [], spigot: [] },
	wolfyutils: { curseforge: [], hangar: [], spigot: [] },
	worldedit: {
		curseforge: ['bukkit-plugins/worldedit', 'mc-mods/worldedit'],
		hangar: ['EngineHub/WorldEdit'],
		spigot: [],
	},
	worldguard: { curseforge: ['bukkit-plugins/worldguard'], hangar: [], spigot: [] },
	'zannaghs-armor-hider': {
		curseforge: ['mc-mods/armor-hider', 'bukkit-plugins/armor-hider-plugin'],
		hangar: ['zannagh/armor-hider'],
		spigot: [],
	},

	// Mods
	'3dskinlayers': { curseforge: [], hangar: [], spigot: [] },
	appleskin: { curseforge: ['mc-mods/appleskin'], hangar: [], spigot: [] },
	'architectury-api': { curseforge: ['mc-mods/architectury-api'], hangar: [], spigot: [] },
	badoptimizations: { curseforge: ['mc-mods/badoptimizations'], hangar: [], spigot: [] },
	balm: { curseforge: ['mc-mods/balm'], hangar: [], spigot: [] },
	'bookshelf-lib': { curseforge: ['mc-mods/bookshelf'], hangar: [], spigot: [] },
	'chat-heads': { curseforge: ['mc-mods/chat-heads'], hangar: [], spigot: [] },
	'cloth-config': {
		curseforge: ['mc-mods/cloth-config', 'mc-mods/cloth-config-legacy'],
		hangar: [],
		spigot: [],
	},
	clumps: { curseforge: ['mc-mods/clumps'], hangar: [], spigot: [] },
	collective: {
		curseforge: ['mc-mods/collective', 'mc-mods/collective-fabric'],
		hangar: [],
		spigot: [],
	},
	continuity: { curseforge: ['mc-mods/continuity'], hangar: [], spigot: [] },
	controlling: { curseforge: ['mc-mods/controlling'], hangar: [], spigot: [] },
	create: { curseforge: ['mc-mods/create'], hangar: [], spigot: [] },
	creativecore: { curseforge: ['mc-mods/creativecore'], hangar: [], spigot: [] },
	distanthorizons: { curseforge: ['mc-mods/distant-horizons'], hangar: [], spigot: [] },
	'dynamic-fps': { curseforge: ['mc-mods/dynamic-fps'], hangar: [], spigot: [] },
	emi: { curseforge: ['mc-mods/emi'], hangar: [], spigot: [] },
	'entity-model-features': {
		curseforge: ['mc-mods/entity-model-features'],
		hangar: [],
		spigot: [],
	},
	entityculling: {
		curseforge: ['bukkit-plugins/entityculling', 'mc-mods/entityculling'],
		hangar: [],
		spigot: [],
	},
	entitytexturefeatures: {
		curseforge: ['mc-mods/entity-texture-features-fabric'],
		hangar: [],
		spigot: [],
	},
	essential: { curseforge: ['mc-mods/essential-mod'], hangar: [], spigot: [] },
	'fabric-api': { curseforge: ['mc-mods/fabric-api'], hangar: [], spigot: [] },
	'fabric-language-kotlin': {
		curseforge: ['mc-mods/fabric-language-kotlin'],
		hangar: [],
		spigot: [],
	},
	fancymenu: {
		curseforge: ['mc-mods/fancymenu', 'mc-mods/fancymenu-fabric'],
		hangar: [],
		spigot: [],
	},
	'ferrite-core': {
		curseforge: ['mc-mods/ferritecore', 'mc-mods/ferritecore-fabric'],
		hangar: [],
		spigot: [],
	},
	'forge-config-api-port': {
		curseforge: ['mc-mods/forge-config-api-port'],
		hangar: [],
		spigot: [],
	},
	'fzzy-config': { curseforge: ['mc-mods/fzzy-config'], hangar: [], spigot: [] },
	geckolib: { curseforge: ['mc-mods/geckolib'], hangar: [], spigot: [] },
	immediatelyfast: { curseforge: ['mc-mods/immediatelyfast'], hangar: [], spigot: [] },
	indium: { curseforge: ['mc-mods/indium'], hangar: [], spigot: [] },
	'inventory-profiles-next': {
		curseforge: ['mc-mods/inventory-profiles-next'],
		hangar: [],
		spigot: [],
	},
	iris: { curseforge: ['mc-mods/irisshaders'], hangar: [], spigot: [] },
	jade: { curseforge: ['mc-mods/jade'], hangar: [], spigot: [] },
	jei: { curseforge: ['mc-mods/jei'], hangar: [], spigot: [] },
	konkrete: { curseforge: ['mc-mods/konkrete', 'mc-mods/konkrete-fabric'], hangar: [], spigot: [] },
	'kotlin-for-forge': { curseforge: ['mc-mods/kotlin-for-forge'], hangar: [], spigot: [] },
	krypton: { curseforge: ['mc-mods/krypton'], hangar: [], spigot: [] },
	lambdynamiclights: { curseforge: ['mc-mods/lambdynamiclights'], hangar: [], spigot: [] },
	'language-reload': { curseforge: ['mc-mods/language-reload'], hangar: [], spigot: [] },
	lithium: { curseforge: ['mc-mods/lithium'], hangar: [], spigot: [] },
	melody: { curseforge: ['mc-mods/melody'], hangar: [], spigot: [] },
	modernfix: { curseforge: ['mc-mods/modernfix'], hangar: [], spigot: [] },
	modmenu: { curseforge: ['mc-mods/modmenu'], hangar: [], spigot: [] },
	moonlight: { curseforge: ['mc-mods/selene'], hangar: [], spigot: [] },
	moreculling: { curseforge: ['mc-mods/moreculling'], hangar: [], spigot: [] },
	'mouse-tweaks': { curseforge: ['mc-mods/mouse-tweaks'], hangar: [], spigot: [] },
	'no-chat-reports': { curseforge: ['mc-mods/no-chat-reports'], hangar: [], spigot: [] },
	'not-enough-animations': {
		curseforge: ['mc-mods/not-enough-animations'],
		hangar: [],
		spigot: [],
	},
	'owo-lib': { curseforge: ['mc-mods/owo-lib'], hangar: [], spigot: [] },
	'placeholder-api': { curseforge: ['mc-mods/text-placeholder-api'], hangar: [], spigot: [] },
	'presence-footsteps': { curseforge: ['mc-mods/presence-footsteps'], hangar: [], spigot: [] },
	'puzzles-lib': { curseforge: ['mc-mods/puzzles-lib'], hangar: [], spigot: [] },
	'reeses-sodium-options': {
		curseforge: ['mc-mods/reeses-sodium-options'],
		hangar: [],
		spigot: [],
	},
	searchables: { curseforge: ['mc-mods/searchables'], hangar: [], spigot: [] },
	sodium: { curseforge: ['mc-mods/sodium'], hangar: [], spigot: [] },
	'sodium-extra': { curseforge: ['mc-mods/sodium-extra'], hangar: [], spigot: [] },
	'sound-physics-remastered': {
		curseforge: ['mc-mods/sound-physics-remastered'],
		hangar: [],
		spigot: [],
	},
	terrablender: {
		curseforge: [
			'mc-mods/terrablender',
			'mc-mods/terrablender-neoforge',
			'mc-mods/terrablender-fabric',
		],
		hangar: [],
		spigot: [],
	},
	'veinminer-client': { curseforge: ['mc-mods/veinminer-hotkey'], hangar: [], spigot: [] },
	waystones: { curseforge: ['mc-mods/waystones'], hangar: [], spigot: [] },
	'xaeros-minimap': { curseforge: ['mc-mods/xaeros-minimap'], hangar: [], spigot: [] },
	'xaeros-world-map': { curseforge: ['mc-mods/xaeros-world-map'], hangar: [], spigot: [] },
	yacl: { curseforge: ['mc-mods/yacl'], hangar: [], spigot: [] },
	zoomify: { curseforge: ['mc-mods/zoomify'], hangar: [], spigot: [] },

	// Modpacks
	battlearmorytacz: { curseforge: [], hangar: [], spigot: [] },
	'better-mc-fabric-bmc2': {
		curseforge: ['modpacks/better-mc-fabric-bmc2'],
		hangar: [],
		spigot: [],
	},
	'better-mc-forge-bmc4': { curseforge: ['modpacks/better-mc-forge-bmc4'], hangar: [], spigot: [] },
	'cave-horror-project-modpack': {
		curseforge: ['modpacks/cave-horror-project'],
		hangar: [],
		spigot: [],
	},
	'cobblemon-fabric': { curseforge: ['modpacks/cobblemon-fabric'], hangar: [], spigot: [] },
	cobbleverse: { curseforge: ['modpacks/cobbleverse-cobblemon'], hangar: [], spigot: [] },
	'fabulously-optimized': { curseforge: ['modpacks/fabulously-optimized'], hangar: [], spigot: [] },
	'optifabric-modpack': { curseforge: ['modpacks/optifabric-modpack'], hangar: [], spigot: [] },
	'prominence-2-fabric': {
		curseforge: ['modpacks/prominence-2-hasturian-era'],
		hangar: [],
		spigot: [],
	},
	'skyblock-enhanced': { curseforge: ['modpacks/skyblock-enhanced'], hangar: [], spigot: [] },
	'slimes-adventure': { curseforge: ['modpacks/slimes-adventure'], hangar: [], spigot: [] },
	sodiumplus: { curseforge: [], hangar: [], spigot: [] },
	'the-pixelmon-modpack': { curseforge: ['modpacks/the-pixelmon-modpack'], hangar: [], spigot: [] },
	'vanilla-perfected': {
		curseforge: ['modpacks/vanilla-perfected-curseforge-edition'],
		hangar: [],
		spigot: [],
	},
	'zombie-invade-100-days': { curseforge: [], hangar: [], spigot: [] },

	// Resource packs
	'better-leaves': {
		curseforge: [
			'texture-packs/motschens-better-leaves',
			'texture-packs/motschens-better-leaves-programmer-art',
		],
		hangar: [],
		spigot: [],
	},
	'chat-reporting-helper': {
		curseforge: ['texture-packs/chat-reporting-helper'],
		hangar: [],
		spigot: [],
	},
	'cobblemon-interface': {
		curseforge: [
			'texture-packs/cobblemon-interface-modded',
			'texture-packs/cobblemon-interface-recolored',
		],
		hangar: [],
		spigot: [],
	},
	'default-dark-mode': { curseforge: ['texture-packs/default-dark-mode'], hangar: [], spigot: [] },
	'dramatic-skys': { curseforge: ['texture-packs/dramatic-skys'], hangar: [], spigot: [] },
	e19_cobblemon_minimap_icons: {
		curseforge: ['texture-packs/e19-cobblemon-minimap-icons'],
		hangar: [],
		spigot: [],
	},
	'fancy-crops': { curseforge: ['texture-packs/fancy-crops'], hangar: [], spigot: [] },
	'fast-better-grass': { curseforge: ['texture-packs/fast-better-grass'], hangar: [], spigot: [] },
	'fresh-animations': { curseforge: ['texture-packs/fresh-animations'], hangar: [], spigot: [] },
	'fresh-animations-extensions': {
		curseforge: ['texture-packs/fresh-animations-extensions'],
		hangar: [],
		spigot: [],
	},
	'fullbright-ub': { curseforge: ['texture-packs/fullbright-ub'], hangar: [], spigot: [] },
	'low-on-fire': { curseforge: ['texture-packs/low-on-fire'], hangar: [], spigot: [] },
	'new-glowing-ores': { curseforge: ['texture-packs/new-glowing-ores'], hangar: [], spigot: [] },
	'translations-for-sodium': {
		curseforge: ['texture-packs/translations-for-sodium'],
		hangar: [],
		spigot: [],
	},
	'tras-fresh-player': { curseforge: ['texture-packs/fresh-moves'], hangar: [], spigot: [] },

	// Shaders
	'bliss-shader': { curseforge: ['shaders/bliss-shader'], hangar: [], spigot: [] },
	'bsl-shaders': { curseforge: ['shaders/bsl-shaders'], hangar: [], spigot: [] },
	'complementary-reimagined': {
		curseforge: ['shaders/complementary-reimagined'],
		hangar: [],
		spigot: [],
	},
	'complementary-unbound': {
		curseforge: ['shaders/complementary-unbound'],
		hangar: [],
		spigot: [],
	},
	'insanity-shader': { curseforge: ['shaders/insanity-shader'], hangar: [], spigot: [] },
	'makeup-ultra-fast-shaders': {
		curseforge: ['shaders/makeup-ultra-fast-shader'],
		hangar: [],
		spigot: [],
	},
	'photon-shader': { curseforge: ['shaders/photon-shader'], hangar: [], spigot: [] },
	'rethinking-voxels': { curseforge: [], hangar: [], spigot: [] },
	'solas-shader': { curseforge: ['shaders/solas-shader'], hangar: [], spigot: [] },
	'super-duper-vanilla': {
		curseforge: ['shaders/super-duper-vanilla-shaders'],
		hangar: [],
		spigot: [],
	},

	// Datapacks
	'cobblemon-additions': { curseforge: [], hangar: [], spigot: [] },
	'dungeons-and-taverns': { curseforge: ['mc-mods/dungeon-and-taverns'], hangar: [], spigot: [] },
	explorify: { curseforge: ['mc-mods/explorify'], hangar: [], spigot: [] },
	geophilic: { curseforge: ['data-packs/geophilic', 'mc-mods/geophilic'], hangar: [], spigot: [] },
	incendium: { curseforge: ['mc-mods/incendium'], hangar: [], spigot: [] },
	'navas-zamega': { curseforge: ['mc-mods/navas-za-megas'], hangar: [], spigot: [] },
	tectonic: { curseforge: ['data-packs/tectonic', 'mc-mods/tectonic'], hangar: [], spigot: [] },
	terralith: { curseforge: ['mc-mods/terralith'], hangar: [], spigot: [] },
	'towns-and-towers': { curseforge: ['mc-mods/towns-and-towers'], hangar: [], spigot: [] },
	trek: { curseforge: ['data-packs/trek', 'mc-mods/trek-mod'], hangar: [], spigot: [] },
}
